{% set version = "4.1.2" %}
{% set patchlevel = "p1" %}
{% set name = "singular" %}

package:
  name: {{ name }}
  version: {{ version }}.{{ patchlevel }}

source:
  fn: {{ name }}-{{ version }}{{ patchlevel }}.tar.gz
  url: http://www.mathematik.uni-kl.de/ftp/pub/Math/Singular/SOURCES/{{ version.replace('.', '-') }}/singular-{{ version }}{{ patchlevel }}.tar.gz
  sha256: b520809ce061059081a973d4a3b102b05863d49c20565d03f638ba5146296d4f

build:
  number: 2
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('singular', max_pin='x.x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - libtool
    - automake
    - pkg-config
  host:
    - gmp
    - mpfr
    - ntl
    - libflint
    - cddlib
    - readline
    - sed
  run:
    - gmp
    - mpfr
    - ntl
    - libflint
    - cddlib
    - readline

test:
  commands:
    - test -f ${PREFIX}/include/singular/Singular/libsingular.h
    - test -f ${PREFIX}/lib/libSingular.a
    - test -f ${PREFIX}/lib/libSingular.dylib     # [osx]
    - test -f ${PREFIX}/lib/libSingular.so        # [linux]

about:
  home: https://www.singular.uni-kl.de/
  license: GPLv2+
  license_file: COPYING
  summary: | 
    Singular is a computer algebra system for polynomial computations, with special emphasis
    on commutative and non-commutative algebra, algebraic geometry, and singularity theory
  dev_url: https://github.com/Singular/Sources

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
