appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: JqqRa1iafJW7iuI/R5H3lmo4wHnw2ZoISzvcxbVWC0Rth8MAoAiPp/ExyPgCBWfGfKZEtS3kRATuzSCtRfJFVbIiiIR2td+x3Rua+R+VWxpYLUUWn0wXxEFwzDgIrGnqtgiBOW/0YKMvEU2oz4yqUHMCO3AQUYGZ0d9qyd4viXizGt4Qa845nWnja2m5v0HikP0MKm2ioO+zycrpY1s3LS8K6xTEj3vABlL/OBgc7XowwSUdAV0e86MelZzDXPvmxGNXg+DwFdjQ5mrVlKTg22VpWNSRusk82KNOf+yrp/6qvDRmwW81O5Rl7DeBpnar3ryxoBhv7jIUU3kFtMV9Yb2+Sw4c6AY7IqudPZYG2sYSdZuYq169tRmtlcqrg8k6BO2U4wPhPAPUoWdpLdvqLr1IiPE9YIX45q+J1MS8++iqAiH19Ncn/NznchV0q1E8vH2YSF43rq5P0Czwd+kr4wfKIbTDH7zJXOABsVtLUI8nVCgJTBwGKIcWuaxxhJJw4EI+Ziq2vtxZ5CcsEgNavAPZppO9zNPM4Y0Mh0yNQyH3eqhOpjtZcmtMLRV4NZhW6RQWHw/CfNGBVLWKOamIDzg5J172UI2wKegVAfAYNCROYqhxQobS17mJ4aqVKew8S3QXkAU/mnmbZepovUM2gZN5pUnSdsYGF4mROxy/fe4=}
